[package]
name = "kissmey"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.10"
# diesel = { version = "2.0.3", features = ["postgres"] }
percent-encoding = "2.2.0"
sea-orm = { version = "0.11.0", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"] }
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"


# [target.x86_64-pc-windows-msvc.pq]
# rustc-link-search = ["C:\\Program Files\\PostgreSQL\\13\\lib"]
# rustc-link-lib = ["libpq"]
